### ISSUE TITLE
🗓️ Standardize how dates handled

### ISSUE THREAD

**Issue by JFWooten4** [WhyDRS/Taking-Stock#4]
I've tried to organize things into a `[[YEAR]] / [[MONTH]] // [[DAY]].md` scheme because that's what I'm most familiar with personally.

However, I've only really seen data management in the context of organizing blog posts. While the standard format might work well for a benevolent single contributor, it might not be the best for groups. 💭

@tehchives has started including interviewee/guest names in the episode titles, which I think is a stellar idea 🌌[^int]

![Screenshot From 2024-10-17 13-16-35](https://github.com/user-attachments/assets/209ee451-da6b-47b1-ba2e-89732842c02a)

![Screenshot From 2024-10-17 13-15-41](https://github.com/user-attachments/assets/97f6143a-422f-47fc-bf06-a63461e1a5d7)
🧠

[^int]: In general, I think the interview format is an exceptional tool to draw out specific, timely, and applicable experiences from the friends we have outside DRS. Namely, I think they allow us to deeply understand opinions which might not get voiced in a collective conversation. 🗣️ Some of the brightest minds stay quiet in these group environments, and a prudent curation of individual viewpoints might just serve our efforts to rectify markets most efficiently.

However, just wanted to start the conversation here and attempt to have some things formalized, so that the arbitrary folder / naming structure I initialized things with doesn't stay in place without cause. 🤝🏼

**Comment by tehchives** [comment]
Using the international format is probably smarter long term. Helps to time-proof things and keep them logical! I'm used to the wacky m/d/y format which America has normalized, myself, but hopefully we see them catch up to the rest of the world in these notational regards. Looking at you, Imperial measurements!

**Comment by JFWooten4** [comment]
Thanks @tehchives for the long-term perspective! While I understand that GitHub sends you directly to the Oct folder as the only folder in `2024`, it will actually show the parent once another file/folder is in `parent`.

For exemplification, I've [moved](https://github.com/WhyDRS/Taking-Stock/commit/0e01f8b921718ab1cfb9ba31b1311521fbedcd78) some of the community items into [`TS/2024`](https://github.com/WhyDRS/Taking-Stock/tree/main/2024).[^q] With this context, I was wondering what you think about the underlying doc names.

I love that you've included people's names/guest info in the titles. However, for someone looking back, this introduces the quandary of alphabetic ordering based on something other than dates. It's my view that this isn't the most ideal if searching for specific info, as you will likely need a `ctrl+f` search to find anything after 50 weeks of eps.

What do you think? Does that make sense? Might I propose this scheme, based on the info above:

> 18: Gorillionaire2.md

> 21: Ankit of XXIM.md

etc. 🗓️🌌🫂

[^q]: Perhaps something like this could best live in a pending [questions](https://github.com/WhyDRS/DAO-docs/tree/main/questions) folder, as this has been pushed back for a few weeks, potentially due to only a couple "AMA" chat questions.

**Comment by tehchives** [comment]
Yes, makes sense! You're 100% right that your suggestion would be cleaner. If we have [year] -> [month] -> [day, guest] that would make for easiest navigating.

At the moment, we don't have any other preplanned guests or weekly topics, so this would be a great time to take advantage of the pending topics folder you suggest as well. I doubt we'll often be scheduling guests less than a week in advance, so we could habitualize pulling items out of that folder and adding them to the schedule.

**Comment by JFWooten4** [comment]
Solved by #5
